### ISSUE TITLE
無法 Convert Template

### ISSUE THREAD

**Issue by lucemia** [livingbio/web-stories-wp#48]
```
node bin/commander.js generate-template > template.json
(node:65312) UnhandledPromiseRejectionWarning: TypeError: pages is not iterable
    at Command.generateTemplate (file:///Users/davidchen/repo/web-stories-wp/bin/utils/generateTemplate.js:60:22)
    at Command.listener [as _actionHandler] (/Users/davidchen/repo/web-stories-wp/node_modules/commander/index.js:413:31)
    at Command._parseCommand (/Users/davidchen/repo/web-stories-wp/node_modules/commander/index.js:914:14)
    at Command._dispatchSubcommand (/Users/davidchen/repo/web-stories-wp/node_modules/commander/index.js:865:18)
    at Command._parseCommand (/Users/davidchen/repo/web-stories-wp/node_modules/commander/index.js:882:12)
    at Command.parse (/Users/davidchen/repo/web-stories-wp/node_modules/commander/index.js:717:10)
    at file:///Users/davidchen/repo/web-stories-wp/bin/commander.js:155:9
    at ModuleJob.run (internal/modules/esm/module_job.js:138:23)
    at async Loader.import (internal/modules/esm/loader.js:178:24)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:65312) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:65312) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```
新作了兩個 Template 要實驗，輸入 cmd 後沒有等待就直接噴 Exception

**Comment by vickyliin** [comment]
啊，應該是我讀 stdin 拉出 function 沒測到... 我測測看

**Comment by vickyliin** [comment]
fixed #23
